backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Personal", "Tech", "Familia", "Belleza"] }
      - { label: "Resumen", name: "excerpt", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }